import * as React from 'react';
import { SVGProps } from 'react';
const SvgCategory = (props: SVGProps<SVGSVGElement>) => (
  <svg
    width={24}
    height={24}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
    focusable="false"
    {...props}
  >
    <rect
      x={3.5}
      y={4}
      width={7}
      height={7}
      rx={2.5}
      stroke="currentColor"
      strokeWidth={1.5}
    />
    <rect
      x={3.5}
      y={14}
      width={7}
      height={7}
      rx={2.5}
      stroke="currentColor"
      strokeWidth={1.5}
    />
    <rect
      x={13.5}
      y={4}
      width={7}
      height={7}
      rx={2.5}
      stroke="currentColor"
      strokeWidth={1.5}
    />
    <rect
      x={13.5}
      y={14}
      width={7}
      height={7}
      rx={2.5}
      stroke="currentColor"
      strokeWidth={1.5}
    />
  </svg>
);
export default SvgCategory;
